config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'jokes#index'
	resources :jokes
	get 'about' => 'static_pages#about'
	get 'random' => 'static_pages#random'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joke.rb
class Joke < ApplicationRecord
	validates :jokes, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
	def index
		@jokes=Joke.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)		
	end
	
	def edit
 	 @joke = Joke.find(params[:id])
	end
	def create
		@joke=Joke.create(joke_params)
		redirect_to root_path
	end
		
		def update
 	 @joke = Joke.find(params[:id])
  	if @joke.update(joke_params)
    redirect_to root_path
  	else
    redirect_to edit_joke_path(params[:id])
  	end
	end
	def destroy
  		@joke = Joke.find(params[:id])
  		@joke.destroy
  		redirect_to root_path
	end
	def random
 	 @joke = Joke.order("RANDOM()").first

	end
	
	private
	def joke_params
		params.require(:joke).permit(:jokes,:author)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about

  end

  def random
  		@joke = Joke.order("RANDOM()").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/jokes/edit.html.erb
<h1>Edit Joke</h1>

<%= simple_form_for @joke, method: :patch do |f| %>
<%= f.input :jokes %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/jokes/index.html.erb
<center><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" style="margin:0 auto">
  Add a Joke
</button></center></br>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Joke title</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for Joke.new do |f| %>
  <%= f.input :jokes %>
  <%= f.input :author %>
  <%= f.submit 'Submit',class: 'btn btn-primary' %>
<% end %>
      </div>
    </div>
  </div>
</div>
<% @jokes.each do |joke| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= simple_format joke.jokes %></p>
        <small>by <%= joke.author %></small>
      </blockquote>
      <br>
      <!-- <div class="btn-group" role="group">
      <%= link_to 'Delete', joke_path(joke),method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
      <%= link_to 'Revise', edit_joke_path(joke), class: 'btn btn-sm btn-success' %>
      </div>-->
    </div>
  </div>
<% end %>
<div class = "text-center">
  <%= will_paginate @jokes %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
  
    <title>Postjoke</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div id = "wrap">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="color: #337AB7;"><i class="fa fa-wpforms" aria-hidden="true"></i>Post JOKES</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'All Jokes', root_path %></li>
    
      <li><% link_to 'Tickle', random_path %></li>
    
    <li><%= link_to 'Tickle', random_path %></li>
    
    <li><%= link_to 'About Us', about_path %></li>
  </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  

  <%= yield %>
  
</div>

<footer class="footer text-center">
  <div class="container">
    <div class = "row">
      <div class = "col-xs-12 col-md-4">
        <h4>Contact</h4>
        <p><a href="mailto:ushakya3@gmail.com">ushakya3@gmail.com</a></p>
      </div>
      <div class = "col-xs-12 col-md-4">
        <h4>© Ujjwal Shakya 2016</h4>
        <p>All Rights Reserved</p>
      </div>

      <div class = "col-xs-12 col-md-4">
        <h4>Join Us</h4>
        <div class="social-buttons">
          <a href = "https://www.facebook.com/groups/postjoke/"><i class="fa fa-facebook-official social fa-2x" ></i></a>	
        </div>
      </div>
          </div>
  </div>
</footer>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="about">
<h3 align="center">About Post Jokes</h3>
<p>It's a group where you get to read and post awesome jokes. You can add a couple of those you know which can bring a smile to someone's face. So, it's a cool place to hang out, have fun.</br>

"At Post jokes, we create a smile."</br>
so, help us create place where tears are just a sign of extreme laughter XD</br>
✰✰✰✰✰Request From Admin✰✰✰✰✰</br>
------------------------------------------------------------</br>
1. Anyone can post jokes, trolls</br>
2. Advertisement is strictly prohibited.</br>
3. Don't post unnecessary links.</br>
4. Nudity and vulgar post are deleted and then
s/he is out of the group and banned.</br>
5. Unnecessary posts, comments and 
arguments are also not allowed..</br>
6. Please be Friendly With each others.</br>
7. Please do not humiliate Nepali public figures, these days Anmol k.c is been humiliated. he is doing good in film industry tho.. la thik cha he might have attitude</br>
yo ta jasko pani huncha ni more or less if someone dislikes then leave it do not provoke in personal matter...</br>
if any indian public figure is trolled yeha birodh garne haru ko line lagcha...</br>

Rules must be followed thank-you else we have to do what we are meant to do. </br>

#admin </br>

Welcome everyone!</br>
P.S. most of the admins are single</p>
</div></br>

app/views/static_pages/random.html.erb
<% if @joke.present? %>
  <%= link_to 'Tickle', random_path, class: 'btn btn-primary btn-block', style: "height: 30px; width: 100px;margin:0 auto",'data-no-turbolink' => true %></br>
    
  <div class="panel panel-default" data-no-turbolink>
    <div class="panel-body">
      <blockquote>
        <p><%= simple_format @joke.jokes %></p>
        <small>by <%= @joke.author %></small>
      </blockquote>
        
      <br>

      <!-- <div class="btn-group" role="group">
        <%= link_to 'Delete', joke_path(@joke), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_joke_path(@joke), class: 'btn btn-sm btn-success' %>
      </div>-->
    </div>
  </div>
 <% end %>  